packages:
  - "packages/ai-sdk"
  - "packages/bridge"
  - "packages/chat-adapter"
  - "packages/cloudflare"
  - "packages/pickle"
  - "packages/state-file"
  - "packages/state-indexeddb"
  - "packages/state-memory"
  - "packages/state-simple"
  - "packages/state-sqlite"
  - "bots/*"
  - "examples/*"
