export const OPENCLAW_GATEWAY_METHOD_FAMILIES = [
  "system",
  "models",
  "usage",
  "channels",
  "messaging",
  "talk",
  "secrets",
  "config",
  "update",
  "wizard",
  "agents",
  "tasks",
  "artifacts",
  "environments",
  "sessions",
  "device-pairing",
  "node-pairing",
  "approvals",
  "automation",
  "skills",
  "tools",
] as const;

export const OPENCLAW_GATEWAY_COMMON_METHODS = [
  "health",
  "diagnostics.stability",
  "status",
  "gateway.identity.get",
  "system-presence",
  "system-event",
  "last-heartbeat",
  "set-heartbeats",
  "models.list",
  "usage.status",
  "usage.cost",
  "doctor.memory.status",
  "doctor.memory.remHarness",
  "sessions.usage",
  "sessions.usage.timeseries",
  "sessions.usage.logs",
  "channels.status",
  "channels.logout",
  "web.login.start",
  "web.login.wait",
  "push.test",
  "voicewake.get",
  "voicewake.set",
  "send",
  "logs.tail",
  "talk.catalog",
  "talk.config",
  "talk.session.create",
  "talk.session.join",
  "talk.session.appendAudio",
  "talk.session.startTurn",
  "talk.session.endTurn",
  "talk.session.cancelTurn",
  "talk.session.cancelOutput",
  "talk.session.submitToolResult",
  "talk.session.close",
  "talk.mode",
  "talk.client.create",
  "talk.client.toolCall",
  "talk.event",
  "talk.speak",
  "tts.status",
  "tts.providers",
  "tts.enable",
  "tts.disable",
  "tts.setProvider",
  "tts.convert",
  "secrets.reload",
  "secrets.resolve",
  "config.get",
  "config.set",
  "config.patch",
  "config.apply",
  "config.schema",
  "config.schema.lookup",
  "update.run",
  "update.status",
  "wizard.start",
  "wizard.next",
  "wizard.status",
  "wizard.cancel",
  "agents.list",
  "agents.create",
  "agents.update",
  "agents.delete",
  "agents.files.list",
  "agents.files.get",
  "agents.files.set",
  "tasks.list",
  "tasks.get",
  "tasks.cancel",
  "artifacts.list",
  "artifacts.get",
  "artifacts.download",
  "environments.list",
  "environments.status",
  "agent.identity.get",
  "agent.wait",
  "sessions.list",
  "sessions.subscribe",
  "sessions.unsubscribe",
  "sessions.messages.subscribe",
  "sessions.messages.unsubscribe",
  "sessions.preview",
  "sessions.describe",
  "sessions.resolve",
  "sessions.create",
  "sessions.steer",
  "sessions.abort",
  "sessions.patch",
  "sessions.reset",
  "sessions.delete",
  "sessions.compact",
  "sessions.get",
  "chat.history",
  "chat.send",
  "chat.abort",
  "chat.inject",
  "device.pair.list",
  "device.pair.approve",
  "device.pair.reject",
  "device.pair.remove",
  "device.token.rotate",
  "device.token.revoke",
  "node.pair.request",
  "node.pair.list",
  "node.pair.approve",
  "node.pair.reject",
  "node.pair.remove",
  "node.pair.verify",
  "node.list",
  "node.describe",
  "node.rename",
  "node.invoke",
  "node.invoke.result",
  "node.event",
  "node.pending.pull",
  "node.pending.ack",
  "node.pending.enqueue",
  "node.pending.drain",
  "exec.approval.request",
  "exec.approval.get",
  "exec.approval.list",
  "exec.approval.resolve",
  "exec.approval.waitDecision",
  "exec.approvals.get",
  "exec.approvals.set",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "plugin.approval.request",
  "plugin.approval.list",
  "plugin.approval.waitDecision",
  "plugin.approval.resolve",
  "wake",
  "cron.get",
  "cron.list",
  "cron.status",
  "cron.add",
  "cron.update",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "commands.list",
  "skills.status",
  "skills.search",
  "skills.detail",
  "skills.bins",
  "skills.upload.begin",
  "skills.upload.chunk",
  "skills.upload.commit",
  "skills.install",
  "skills.update",
  "tools.catalog",
  "tools.effective",
  "tools.invoke",
] as const;

export const OPENCLAW_GATEWAY_EVENT_FAMILIES = [
  "chat",
  "session.message",
  "session.operation",
  "session.tool",
  "sessions.changed",
  "presence",
  "tick",
  "health",
  "heartbeat",
  "cron",
  "shutdown",
  "node.pair.requested",
  "node.pair.resolved",
  "node.invoke.request",
  "device.pair.requested",
  "device.pair.resolved",
  "voicewake.changed",
  "exec.approval.requested",
  "exec.approval.resolved",
  "plugin.approval.requested",
  "plugin.approval.resolved",
] as const;

export const OPENCLAW_BRIDGE_COVERAGE = {
  eventFamilies: {
    approval: ["exec.approval.requested", "exec.approval.resolved", "plugin.approval.requested", "plugin.approval.resolved"],
    ignoredOperational: ["sessions.changed", "presence", "tick", "health", "heartbeat", "cron", "shutdown", "node.pair.requested", "node.pair.resolved", "node.invoke.request", "device.pair.requested", "device.pair.resolved", "voicewake.changed"],
    stream: ["chat", "session.message", "session.operation", "session.tool"],
  },
  methodAccess: {
    pluginRuntimeAdapters: ["agents.list", "sessions.list", "sessions.create", "chat.history", "exec.approval.resolve", "plugin.approval.resolve"],
    commonGatewayMethods: OPENCLAW_GATEWAY_COMMON_METHODS,
    beeperTurnDispatch: "runtime.channel.turn.runAssembled",
  },
  source: ".upstream/openclaw/docs/gateway/protocol.md",
} as const;

export type OpenClawGatewayMethodFamily = typeof OPENCLAW_GATEWAY_METHOD_FAMILIES[number];
export type OpenClawGatewayCommonMethod = typeof OPENCLAW_GATEWAY_COMMON_METHODS[number];
export type OpenClawGatewayEventFamily = typeof OPENCLAW_GATEWAY_EVENT_FAMILIES[number];
