// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.

import type {
  MatrixAccountDataResult,
  MatrixApplySyncResponseOptions,
  MatrixBanUserOptions,
  MatrixBeeperStreamOptions,
  MatrixCoreInitOptions,
  MatrixCreateBeeperStreamOptions,
  MatrixCreateBeeperStreamResult,
  MatrixCreateRoomOptions,
  MatrixCreateRoomResult,
  MatrixCryptoStatus,
  MatrixDeleteMessageOptions,
  MatrixDownloadEncryptedMediaOptions,
  MatrixDownloadMediaOptions,
  MatrixDownloadMediaResult,
  MatrixDownloadMediaThumbnailOptions,
  MatrixEditMessageOptions,
  MatrixFetchMessageOptions,
  MatrixFetchMessageResult,
  MatrixFetchMessagesOptions,
  MatrixFetchMessagesResult,
  MatrixFetchRoomMembersOptions,
  MatrixFetchRoomOptions,
  MatrixFetchRoomStateEventOptions,
  MatrixFetchRoomStateOptions,
  MatrixFetchRoomStateResult,
  MatrixGetAccountDataOptions,
  MatrixGetRoomAccountDataOptions,
  MatrixGetUserOptions,
  MatrixInviteUserOptions,
  MatrixJoinRoomOptions,
  MatrixJoinRoomResult,
  MatrixJoinedRoomsResult,
  MatrixKickUserOptions,
  MatrixLeaveRoomOptions,
  MatrixListPublicRoomsOptions,
  MatrixListPublicRoomsResult,
  MatrixListRoomThreadsOptions,
  MatrixListRoomThreadsResult,
  MatrixMarkReadOptions,
  MatrixOpenDMOptions,
  MatrixOpenDMResult,
  MatrixOwnAvatarURLResult,
  MatrixOwnDisplayNameResult,
  MatrixRawMessage,
  MatrixRawRequestOptions,
  MatrixRawRequestResult,
  MatrixReactionOptions,
  MatrixRegisterBeeperStreamOptions,
  MatrixResolveRoomAliasOptions,
  MatrixResolveRoomAliasResult,
  MatrixRoomInfo,
  MatrixRoomMembersResult,
  MatrixRoomStateEvent,
  MatrixSendEphemeralEventOptions,
  MatrixSendMediaMessageOptions,
  MatrixSendMessageOptions,
  MatrixSendReceiptOptions,
  MatrixSendRoomStateEventOptions,
  MatrixSendToDeviceOptions,
  MatrixSendToDeviceResult,
  MatrixSetAccountDataOptions,
  MatrixSetOwnAvatarURLOptions,
  MatrixSetOwnDisplayNameOptions,
  MatrixSetRoomAccountDataOptions,
  MatrixSyncOnceOptions,
  MatrixSyncStartOptions,
  MatrixTypingOptions,
  MatrixUnbanUserOptions,
  MatrixUploadEncryptedMediaResult,
  MatrixUploadMediaOptions,
  MatrixUploadMediaResult,
  MatrixUserInfo,
  MatrixWhoami,
} from "./generated-runtime-types";

export interface MatrixCoreOperations {
  syncOnce(options?: MatrixSyncOnceOptions): Promise<void>;
  startSync(options?: MatrixSyncStartOptions): Promise<void>;
  stopSync(): Promise<void>;
  init(options: MatrixCoreInitOptions): Promise<MatrixWhoami>;
  whoami(): Promise<MatrixWhoami>;
  logout(): Promise<void>;
  getCryptoStatus(): Promise<MatrixCryptoStatus>;
  rawRequest(options: MatrixRawRequestOptions): Promise<MatrixRawRequestResult>;
  applySyncResponse(options: MatrixApplySyncResponseOptions): Promise<void>;
  getAccountData(options: MatrixGetAccountDataOptions): Promise<MatrixAccountDataResult>;
  setAccountData(options: MatrixSetAccountDataOptions): Promise<void>;
  getRoomAccountData(options: MatrixGetRoomAccountDataOptions): Promise<MatrixAccountDataResult>;
  setRoomAccountData(options: MatrixSetRoomAccountDataOptions): Promise<void>;
  sendToDevice(options: MatrixSendToDeviceOptions): Promise<MatrixSendToDeviceResult>;
  sendReceipt(options: MatrixSendReceiptOptions): Promise<void>;
  postMessage(options: MatrixSendMessageOptions): Promise<MatrixRawMessage>;
  postMediaMessage(options: MatrixSendMediaMessageOptions): Promise<MatrixRawMessage>;
  editMessage(options: MatrixEditMessageOptions): Promise<MatrixRawMessage>;
  deleteMessage(options: MatrixDeleteMessageOptions): Promise<void>;
  addReaction(options: MatrixReactionOptions): Promise<MatrixRawMessage>;
  removeReaction(options: MatrixReactionOptions): Promise<void>;
  sendEphemeralEvent(options: MatrixSendEphemeralEventOptions): Promise<MatrixRawMessage>;
  createBeeperStream(options: MatrixCreateBeeperStreamOptions): Promise<MatrixCreateBeeperStreamResult>;
  registerBeeperStream(options: MatrixRegisterBeeperStreamOptions): Promise<void>;
  publishBeeperStream(options: MatrixBeeperStreamOptions): Promise<void>;
  unsubscribeBeeperStream(options: MatrixBeeperStreamOptions): Promise<void>;
  setTyping(options: MatrixTypingOptions): Promise<void>;
  fetchMessage(options: MatrixFetchMessageOptions): Promise<MatrixFetchMessageResult>;
  fetchMessages(options: MatrixFetchMessagesOptions): Promise<MatrixFetchMessagesResult>;
  markRead(options: MatrixMarkReadOptions): Promise<void>;
  uploadMedia(options: MatrixUploadMediaOptions): Promise<MatrixUploadMediaResult>;
  downloadMedia(options: MatrixDownloadMediaOptions): Promise<MatrixDownloadMediaResult>;
  downloadMediaThumbnail(options: MatrixDownloadMediaThumbnailOptions): Promise<MatrixDownloadMediaResult>;
  uploadEncryptedMedia(options: MatrixUploadMediaOptions): Promise<MatrixUploadEncryptedMediaResult>;
  downloadEncryptedMedia(options: MatrixDownloadEncryptedMediaOptions): Promise<MatrixDownloadMediaResult>;
  createRoom(options: MatrixCreateRoomOptions): Promise<MatrixCreateRoomResult>;
  fetchRoom(options: MatrixFetchRoomOptions): Promise<MatrixRoomInfo>;
  fetchRoomState(options: MatrixFetchRoomStateOptions): Promise<MatrixFetchRoomStateResult>;
  fetchRoomStateEvent(options: MatrixFetchRoomStateEventOptions): Promise<MatrixRoomStateEvent>;
  sendRoomStateEvent(options: MatrixSendRoomStateEventOptions): Promise<MatrixRawMessage>;
  resolveRoomAlias(options: MatrixResolveRoomAliasOptions): Promise<MatrixResolveRoomAliasResult>;
  listPublicRooms(options: MatrixListPublicRoomsOptions): Promise<MatrixListPublicRoomsResult>;
  openDM(options: MatrixOpenDMOptions): Promise<MatrixOpenDMResult>;
  joinRoom(options: MatrixJoinRoomOptions): Promise<MatrixJoinRoomResult>;
  leaveRoom(options: MatrixLeaveRoomOptions): Promise<void>;
  inviteUser(options: MatrixInviteUserOptions): Promise<void>;
  fetchRoomMembers(options: MatrixFetchRoomMembersOptions): Promise<MatrixRoomMembersResult>;
  kickUser(options: MatrixKickUserOptions): Promise<void>;
  banUser(options: MatrixBanUserOptions): Promise<void>;
  unbanUser(options: MatrixUnbanUserOptions): Promise<void>;
  fetchJoinedRooms(): Promise<MatrixJoinedRoomsResult>;
  getUser(options: MatrixGetUserOptions): Promise<MatrixUserInfo>;
  getOwnDisplayName(): Promise<MatrixOwnDisplayNameResult>;
  setOwnDisplayName(options: MatrixSetOwnDisplayNameOptions): Promise<void>;
  getOwnAvatarURL(): Promise<MatrixOwnAvatarURLResult>;
  setOwnAvatarURL(options: MatrixSetOwnAvatarURLOptions): Promise<void>;
  listRoomThreads(options: MatrixListRoomThreadsOptions): Promise<MatrixListRoomThreadsResult>;
  close(): Promise<void>;
}

export abstract class MatrixCoreOperationCaller implements MatrixCoreOperations {
  protected abstract call<T>(operation: string, payload?: unknown): Promise<T>;

  syncOnce(options: MatrixSyncOnceOptions = {}): Promise<void> {
    return this.call<void>("sync_once", options);
  }

  startSync(options: MatrixSyncStartOptions = {}): Promise<void> {
    return this.call<void>("start_sync", options);
  }

  stopSync(): Promise<void> {
    return this.call<void>("stop_sync");
  }

  init(options: MatrixCoreInitOptions): Promise<MatrixWhoami> {
    return this.call<MatrixWhoami>("init", options);
  }

  whoami(): Promise<MatrixWhoami> {
    return this.call<MatrixWhoami>("whoami");
  }

  logout(): Promise<void> {
    return this.call<void>("logout");
  }

  getCryptoStatus(): Promise<MatrixCryptoStatus> {
    return this.call<MatrixCryptoStatus>("get_crypto_status");
  }

  rawRequest(options: MatrixRawRequestOptions): Promise<MatrixRawRequestResult> {
    return this.call<MatrixRawRequestResult>("raw_request", options);
  }

  applySyncResponse(options: MatrixApplySyncResponseOptions): Promise<void> {
    return this.call<void>("apply_sync_response", options);
  }

  getAccountData(options: MatrixGetAccountDataOptions): Promise<MatrixAccountDataResult> {
    return this.call<MatrixAccountDataResult>("get_account_data", options);
  }

  setAccountData(options: MatrixSetAccountDataOptions): Promise<void> {
    return this.call<void>("set_account_data", options);
  }

  getRoomAccountData(options: MatrixGetRoomAccountDataOptions): Promise<MatrixAccountDataResult> {
    return this.call<MatrixAccountDataResult>("get_room_account_data", options);
  }

  setRoomAccountData(options: MatrixSetRoomAccountDataOptions): Promise<void> {
    return this.call<void>("set_room_account_data", options);
  }

  sendToDevice(options: MatrixSendToDeviceOptions): Promise<MatrixSendToDeviceResult> {
    return this.call<MatrixSendToDeviceResult>("send_to_device", options);
  }

  sendReceipt(options: MatrixSendReceiptOptions): Promise<void> {
    return this.call<void>("send_receipt", options);
  }

  postMessage(options: MatrixSendMessageOptions): Promise<MatrixRawMessage> {
    return this.call<MatrixRawMessage>("post_message", options);
  }

  postMediaMessage(options: MatrixSendMediaMessageOptions): Promise<MatrixRawMessage> {
    return this.call<MatrixRawMessage>("post_media_message", options);
  }

  editMessage(options: MatrixEditMessageOptions): Promise<MatrixRawMessage> {
    return this.call<MatrixRawMessage>("edit_message", options);
  }

  deleteMessage(options: MatrixDeleteMessageOptions): Promise<void> {
    return this.call<void>("delete_message", options);
  }

  addReaction(options: MatrixReactionOptions): Promise<MatrixRawMessage> {
    return this.call<MatrixRawMessage>("add_reaction", options);
  }

  removeReaction(options: MatrixReactionOptions): Promise<void> {
    return this.call<void>("remove_reaction", options);
  }

  sendEphemeralEvent(options: MatrixSendEphemeralEventOptions): Promise<MatrixRawMessage> {
    return this.call<MatrixRawMessage>("send_ephemeral_event", options);
  }

  createBeeperStream(options: MatrixCreateBeeperStreamOptions): Promise<MatrixCreateBeeperStreamResult> {
    return this.call<MatrixCreateBeeperStreamResult>("create_beeper_stream", options);
  }

  registerBeeperStream(options: MatrixRegisterBeeperStreamOptions): Promise<void> {
    return this.call<void>("register_beeper_stream", options);
  }

  publishBeeperStream(options: MatrixBeeperStreamOptions): Promise<void> {
    return this.call<void>("publish_beeper_stream", options);
  }

  unsubscribeBeeperStream(options: MatrixBeeperStreamOptions): Promise<void> {
    return this.call<void>("unsubscribe_beeper_stream", options);
  }

  setTyping(options: MatrixTypingOptions): Promise<void> {
    return this.call<void>("set_typing", options);
  }

  fetchMessage(options: MatrixFetchMessageOptions): Promise<MatrixFetchMessageResult> {
    return this.call<MatrixFetchMessageResult>("fetch_message", options);
  }

  fetchMessages(options: MatrixFetchMessagesOptions): Promise<MatrixFetchMessagesResult> {
    return this.call<MatrixFetchMessagesResult>("fetch_messages", options);
  }

  markRead(options: MatrixMarkReadOptions): Promise<void> {
    return this.call<void>("mark_read", options);
  }

  uploadMedia(options: MatrixUploadMediaOptions): Promise<MatrixUploadMediaResult> {
    return this.call<MatrixUploadMediaResult>("upload_media", options);
  }

  downloadMedia(options: MatrixDownloadMediaOptions): Promise<MatrixDownloadMediaResult> {
    return this.call<MatrixDownloadMediaResult>("download_media", options);
  }

  downloadMediaThumbnail(options: MatrixDownloadMediaThumbnailOptions): Promise<MatrixDownloadMediaResult> {
    return this.call<MatrixDownloadMediaResult>("download_media_thumbnail", options);
  }

  uploadEncryptedMedia(options: MatrixUploadMediaOptions): Promise<MatrixUploadEncryptedMediaResult> {
    return this.call<MatrixUploadEncryptedMediaResult>("upload_encrypted_media", options);
  }

  downloadEncryptedMedia(options: MatrixDownloadEncryptedMediaOptions): Promise<MatrixDownloadMediaResult> {
    return this.call<MatrixDownloadMediaResult>("download_encrypted_media", options);
  }

  createRoom(options: MatrixCreateRoomOptions): Promise<MatrixCreateRoomResult> {
    return this.call<MatrixCreateRoomResult>("create_room", options);
  }

  fetchRoom(options: MatrixFetchRoomOptions): Promise<MatrixRoomInfo> {
    return this.call<MatrixRoomInfo>("fetch_room", options);
  }

  fetchRoomState(options: MatrixFetchRoomStateOptions): Promise<MatrixFetchRoomStateResult> {
    return this.call<MatrixFetchRoomStateResult>("fetch_room_state", options);
  }

  fetchRoomStateEvent(options: MatrixFetchRoomStateEventOptions): Promise<MatrixRoomStateEvent> {
    return this.call<MatrixRoomStateEvent>("fetch_room_state_event", options);
  }

  sendRoomStateEvent(options: MatrixSendRoomStateEventOptions): Promise<MatrixRawMessage> {
    return this.call<MatrixRawMessage>("send_room_state_event", options);
  }

  resolveRoomAlias(options: MatrixResolveRoomAliasOptions): Promise<MatrixResolveRoomAliasResult> {
    return this.call<MatrixResolveRoomAliasResult>("resolve_room_alias", options);
  }

  listPublicRooms(options: MatrixListPublicRoomsOptions): Promise<MatrixListPublicRoomsResult> {
    return this.call<MatrixListPublicRoomsResult>("list_public_rooms", options);
  }

  openDM(options: MatrixOpenDMOptions): Promise<MatrixOpenDMResult> {
    return this.call<MatrixOpenDMResult>("open_dm", options);
  }

  joinRoom(options: MatrixJoinRoomOptions): Promise<MatrixJoinRoomResult> {
    return this.call<MatrixJoinRoomResult>("join_room", options);
  }

  leaveRoom(options: MatrixLeaveRoomOptions): Promise<void> {
    return this.call<void>("leave_room", options);
  }

  inviteUser(options: MatrixInviteUserOptions): Promise<void> {
    return this.call<void>("invite_user", options);
  }

  fetchRoomMembers(options: MatrixFetchRoomMembersOptions): Promise<MatrixRoomMembersResult> {
    return this.call<MatrixRoomMembersResult>("fetch_room_members", options);
  }

  kickUser(options: MatrixKickUserOptions): Promise<void> {
    return this.call<void>("kick_user", options);
  }

  banUser(options: MatrixBanUserOptions): Promise<void> {
    return this.call<void>("ban_user", options);
  }

  unbanUser(options: MatrixUnbanUserOptions): Promise<void> {
    return this.call<void>("unban_user", options);
  }

  fetchJoinedRooms(): Promise<MatrixJoinedRoomsResult> {
    return this.call<MatrixJoinedRoomsResult>("fetch_joined_rooms");
  }

  getUser(options: MatrixGetUserOptions): Promise<MatrixUserInfo> {
    return this.call<MatrixUserInfo>("get_user", options);
  }

  getOwnDisplayName(): Promise<MatrixOwnDisplayNameResult> {
    return this.call<MatrixOwnDisplayNameResult>("get_own_display_name");
  }

  setOwnDisplayName(options: MatrixSetOwnDisplayNameOptions): Promise<void> {
    return this.call<void>("set_own_display_name", options);
  }

  getOwnAvatarURL(): Promise<MatrixOwnAvatarURLResult> {
    return this.call<MatrixOwnAvatarURLResult>("get_own_avatar_url");
  }

  setOwnAvatarURL(options: MatrixSetOwnAvatarURLOptions): Promise<void> {
    return this.call<void>("set_own_avatar_url", options);
  }

  listRoomThreads(options: MatrixListRoomThreadsOptions): Promise<MatrixListRoomThreadsResult> {
    return this.call<MatrixListRoomThreadsResult>("list_room_threads", options);
  }

  close(): Promise<void> {
    return this.call<void>("close");
  }

}
