// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.

export interface MatrixEncryptedFileKey {
  alg: "A256CTR";
  ext: true;
  k: string;
  key_ops: ["encrypt", "decrypt"];
  kty: "oct";
}

export interface MatrixEncryptedFile {
  hashes: { sha256: string };
  iv: string;
  key: MatrixEncryptedFileKey;
  url: string;
  v: "v2";
}

export interface MatrixAppserviceNamespace {
  exclusive: boolean;
  regex: string;
}
export interface MatrixAppserviceNamespaces {
  aliases?: MatrixAppserviceNamespace[];
  rooms?: MatrixAppserviceNamespace[];
  users?: MatrixAppserviceNamespace[];
}
export interface MatrixAppserviceRegistration {
  asToken: string;
  hsToken: string;
  id: string;
  msc3202?: boolean;
  msc4190?: boolean;
  namespaces: MatrixAppserviceNamespaces;
  protocols?: string[];
  rateLimited?: boolean;
  senderLocalpart: string;
  url: string;
}
export interface MatrixAppserviceInitOptions {
  homeserver: string;
  homeserverDomain?: string;
  registration: MatrixAppserviceRegistration;
}
export interface MatrixAppserviceInfo {
  botUserId: string;
  id: string;
}
export interface MatrixAppserviceUserOptions {
  userId: string;
}
export interface MatrixAppserviceRoomUserOptions {
  roomId: string;
  userId: string;
}
export interface MatrixAppserviceCreateRoomOptions extends MatrixCreateRoomOptions {
  userId?: string;
}
export interface MatrixAppservicePortalKey {
  id: string;
  receiver?: string;
}
export interface MatrixAppserviceBridgeName {
  beeperBridgeType?: string;
  defaultCommandPrefix?: string;
  defaultPort?: number /* int */;
  displayName: string;
  networkIcon?: string;
  networkId: string;
  networkUrl?: string;
}
export interface MatrixAppserviceCreatePortalRoomOptions {
  avatarUrl?: string;
  autoJoinInvites?: boolean;
  bridge: MatrixAppserviceBridgeName;
  bridgeName?: string;
  initialState?: MatrixRoomStateInput[];
  initialMembers?: string[];
  invite?: string[];
  isDirect?: boolean;
  messageRequest?: boolean;
  name?: string;
  portalKey: MatrixAppservicePortalKey;
  roomType?: string;
  topic?: string;
  userId?: string;
}
export interface MatrixAppserviceCreateManagementRoomOptions {
  autoJoinInvites?: boolean;
  initialMembers?: string[];
  invite?: string[];
  name?: string;
  topic?: string;
  userId?: string;
}
export interface MatrixAppserviceSendMessageOptions {
  content: { [key: string]: unknown };
  eventType?: string;
  roomId: string;
  timestamp?: number /* int64 */;
  transactionId?: string;
  userId?: string;
}
export interface MatrixAppserviceBatchEvent {
  content: { [key: string]: unknown };
  eventId?: string;
  eventType?: string;
  roomId?: string;
  sender: string;
  stateKey?: string;
  timestamp?: number /* int64 */;
}
export interface MatrixAppserviceBatchSendOptions {
  events: MatrixAppserviceBatchEvent[];
  forward?: boolean;
  forwardIfNoMessages?: boolean;
  markReadBy?: string;
  roomId: string;
  sendNotification?: boolean;
}
export interface MatrixAppserviceBatchSendResult {
  eventIds: string[];
  raw: unknown;
}
export interface MatrixAppserviceTransactionOptions {
  transaction: { [key: string]: unknown };
}
export interface MatrixCryptoStatus {
  deviceId?: string;
  hasRecoveryKey: boolean;
  keyBackupVersion?: string;
  pendingDecryptionCount: number /* int */;
  state: "disabled" | "enabled" | "key_backup_updated" | "key_backup_unavailable" | "recovery_cache_unavailable" | "recovery_key_cached" | "recovery_key_loaded" | "recovery_restored" | "recovery_unverified";
  storeBacked: boolean;
  userId?: string;
}
export interface MatrixCoreInitOptions {
  accessToken: string;
  appservice?: MatrixAppserviceInitOptions;
  catchUpOnStart?: boolean;
  deviceId?: string;
  homeserverUrl: string;
  initialSyncMode?: "persisted" | "latest" | "catch_up";
  initialSyncSince?: string;
  pickleKey?: string;
  recoveryKey?: string;
  userId?: string;
  verifyRecoveryOnStart?: boolean;
}
export interface MatrixWhoami {
  userId: string;
  deviceId: string;
}
export interface MatrixUploadMediaOptions {
  bytesBase64: string;
  contentType?: string;
  filename?: string;
}
export interface MatrixSendMediaMessageOptions {
  roomId: string;
  body?: string;
  bytesBase64: string;
  contentType?: string;
  duration?: number /* int */;
  filename?: string;
  height?: number /* int */;
  msgtype?: "m.image" | "m.video" | "m.audio" | "m.file";
  size?: number /* int */;
  threadRootEventId?: string;
  width?: number /* int */;
}
export interface MatrixDownloadMediaOptions {
  contentUri: string;
}
export interface MatrixDownloadMediaThumbnailOptions {
  animated?: boolean;
  contentUri: string;
  height: number /* int */;
  method?: "crop" | "scale" | string;
  width: number /* int */;
}
export interface MatrixDownloadEncryptedMediaOptions {
  file: MatrixEncryptedFile;
}
export interface MatrixSendMessageOptions {
  roomId: string;
  body: string;
  content?: { [key: string]: unknown };
  formattedBody?: string;
  mentions?: MatrixMentions;
  msgtype?: "m.text" | "m.notice" | "m.emote";
  threadRootEventId?: string;
  replyToEventId?: string;
}
export interface MatrixMentions {
  room?: boolean;
  userIds?: string[];
}
export interface MatrixRawMessage {
  eventId: string;
  roomId: string;
  raw: unknown;
}
export interface MatrixCreateBeeperStreamResult {
  descriptor: { [key: string]: unknown };
}
export interface MatrixCreateBeeperStreamOptions {
  roomId: string;
  streamType?: string;
}
export interface MatrixBeeperStreamOptions {
  content?: { [key: string]: unknown};
  eventId: string;
  roomId: string;
}
export interface MatrixRegisterBeeperStreamOptions {
  descriptor: { [key: string]: unknown };
  eventId: string;
  roomId: string;
  subscribers?: MatrixBeeperStreamSubscriber[];
}
export interface MatrixBeeperStreamSubscriber {
  deviceId: string;
  userId: string;
}
export interface MatrixEditMessageOptions {
  roomId: string;
  messageId: string;
  body: string;
  content?: { [key: string]: unknown };
  topLevelContent?: { [key: string]: unknown };
  formattedBody?: string;
  mentions?: MatrixMentions;
  msgtype?: "m.text" | "m.notice" | "m.emote";
}
export interface MatrixSendEphemeralEventOptions {
  content: { [key: string]: unknown };
  eventType: string;
  roomId: string;
  transactionId?: string;
}
export interface MatrixDeleteMessageOptions {
  roomId: string;
  messageId: string;
  reason?: string;
}
export interface MatrixTypingOptions {
  roomId: string;
  typing: boolean;
  timeoutMs?: number /* int */;
}
export interface MatrixFetchMessageOptions {
  roomId: string;
  messageId: string;
}
export interface MatrixFetchMessagesOptions {
  roomId: string;
  cursor?: string;
  direction?: "backward" | "forward";
  limit?: number /* int */;
  threadRootEventId?: string;
}
export interface MatrixMarkReadOptions {
  eventId: string;
  roomId: string;
}
export interface MatrixReactionOptions {
  roomId: string;
  messageId: string;
  emoji: string;
}
export interface MatrixFetchRoomOptions {
  roomId: string;
}
export interface MatrixRoomStateInput {
  content: { [key: string]: unknown };
  stateKey: string;
  type: string;
}
export interface MatrixCreateRoomOptions {
  creationContent?: { [key: string]: unknown };
  initialState?: MatrixRoomStateInput[];
  invite?: string[];
  isDirect?: boolean;
  name?: string;
  preset?: "private_chat" | "public_chat" | "trusted_private_chat" | string;
  roomAliasName?: string;
  roomVersion?: string;
  topic?: string;
  visibility?: "public" | "private" | string;
}
export interface MatrixCreateRoomResult {
  raw: unknown;
  roomId: string;
}
export interface MatrixRoomStateEvent {
  content: { [key: string]: unknown};
  eventId?: string;
  originServerTs?: number /* int64 */;
  raw: unknown;
  roomId: string;
  sender?: string;
  stateKey: string;
  type: string;
}
export interface MatrixFetchRoomStateOptions {
  roomId: string;
}
export interface MatrixFetchRoomStateEventOptions {
  eventType: string;
  roomId: string;
  stateKey?: string;
}
export interface MatrixFetchRoomStateResult {
  events: MatrixRoomStateEvent[];
  raw: unknown;
}
export interface MatrixSendRoomStateEventOptions {
  content: { [key: string]: unknown };
  eventType: string;
  roomId: string;
  stateKey?: string;
}
export interface MatrixResolveRoomAliasOptions {
  alias: string;
}
export interface MatrixResolveRoomAliasResult {
  raw: unknown;
  roomId: string;
  servers: string[];
}
export interface MatrixListPublicRoomsOptions {
  includeAllNetworks?: boolean;
  limit?: number /* int */;
  since?: string;
  thirdPartyInstanceId?: string;
}
export interface MatrixPublicRoom {
  avatarUrl?: string;
  canonicalAlias?: string;
  guestCanJoin: boolean;
  joinRule?: string;
  name?: string;
  numJoinedMembers: number /* int */;
  roomId: string;
  roomType?: string;
  topic?: string;
  worldReadable: boolean;
  roomVersion?: string;
  encryption?: string;
  allowedRoomIds?: string[];
}
export interface MatrixListPublicRoomsResult {
  nextBatch?: string;
  prevBatch?: string;
  raw: unknown;
  rooms: MatrixPublicRoom[];
  totalRoomCountEstimate: number /* int */;
}
export interface MatrixRoomInfo {
  encrypted: boolean;
  directUserId?: string;
  id: string;
  isDM?: boolean;
  joinRule?: string;
  memberCount?: number /* int */;
  name?: string;
  topic?: string;
  raw?: { [key: string]: unknown};
  visibility?: "private" | "workspace" | "external" | "unknown";
}
export interface MatrixOpenDMOptions {
  forceCreate?: boolean;
  userId: string;
}
export interface MatrixJoinRoomOptions {
  roomIdOrAlias: string;
}
export interface MatrixLeaveRoomOptions {
  reason?: string;
  roomId: string;
}
export interface MatrixInviteUserOptions {
  reason?: string;
  roomId: string;
  userId: string;
}
export interface MatrixFetchRoomMembersOptions {
  at?: string;
  membership?: "join" | "invite" | "leave" | "ban" | "knock" | string;
  notMembership?: "join" | "invite" | "leave" | "ban" | "knock" | string;
  roomId: string;
}
export interface MatrixRoomMember {
  avatarUrl?: string;
  displayName?: string;
  membership: string;
  raw: unknown;
  reason?: string;
  userId: string;
}
export interface MatrixRoomMembersResult {
  members: MatrixRoomMember[];
  raw: unknown;
}
export interface MatrixKickUserOptions {
  reason?: string;
  roomId: string;
  userId: string;
}
export interface MatrixBanUserOptions {
  reason?: string;
  redactEvents?: boolean;
  roomId: string;
  userId: string;
}
export interface MatrixUnbanUserOptions {
  reason?: string;
  roomId: string;
  userId: string;
}
export interface MatrixAccountDataResult {
  content: { [key: string]: unknown};
  raw: unknown;
  type: string;
}
export interface MatrixGetAccountDataOptions {
  eventType: string;
}
export interface MatrixSetAccountDataOptions {
  content: { [key: string]: unknown};
  eventType: string;
}
export interface MatrixGetRoomAccountDataOptions {
  eventType: string;
  roomId: string;
}
export interface MatrixSetRoomAccountDataOptions {
  content: { [key: string]: unknown};
  eventType: string;
  roomId: string;
}
export interface MatrixSendToDeviceOptions {
  content?: { [key: string]: unknown};
  eventType: string;
  messages?: { [key: string]: { [key: string]: { [key: string]: unknown}}};
  transactionId?: string;
  userId?: string;
  deviceId?: string;
}
export interface MatrixSendToDeviceResult {
  raw: unknown;
}
export interface MatrixSendReceiptOptions {
  content?: { [key: string]: unknown};
  eventId: string;
  receiptType?: string;
  roomId: string;
  threadId?: string;
}
export interface MatrixRawRequestOptions {
  body?: unknown;
  headers?: { [key: string]: string};
  method?: string;
  path: string;
  query?: { [key: string]: string};
}
export interface MatrixRawRequestResult {
  body?: unknown;
  raw?: unknown;
  status: number /* int */;
  headers?: { [key: string]: string};
}
export interface MatrixSyncOnceOptions {
  beeperStreaming?: boolean;
  replayMissed?: boolean;
  timeoutMs?: number /* int */;
}
export interface MatrixSyncStartOptions {
  beeperStreaming?: boolean;
  retryDelayMs?: number /* int */;
  timeoutMs?: number /* int */;
}
export interface MatrixApplySyncResponseOptions {
  since?: string;
  response: unknown;
}
export interface MatrixListRoomThreadsOptions {
  cursor?: string;
  limit?: number /* int */;
  roomId: string;
}
export interface MatrixRawEvent {
  content: { [key: string]: unknown};
  eventId: string;
  isMe?: boolean;
  originServerTs?: number /* int64 */;
  raw: unknown;
  roomId: string;
  sender: string;
  type: string;
}
export interface MatrixMediaInfo {
  contentType?: string;
  duration?: number /* int64 */;
  height?: number /* int */;
  size?: number /* int64 */;
  width?: number /* int */;
}
export interface MatrixMediaAttachment {
  contentUri?: string;
  encryptedFile?: MatrixEncryptedFile;
  filename?: string;
  info?: MatrixMediaInfo;
  msgtype: "m.image" | "m.video" | "m.audio" | "m.file";
}
export interface MatrixMessageEvent extends MatrixRawEvent {
  attachments?: MatrixMediaAttachment[];
  body: string;
  formattedBody?: string;
  isEncrypted?: boolean;
  isEdited?: boolean;
  mentions?: MatrixMentions;
  msgtype: string;
  relation?: MatrixRelation;
  replaces?: string;
  replyTo?: string;
  threadRootEventId?: string;
}
export interface MatrixRelation {
  eventId: string;
  isFallback?: boolean;
  key?: string;
  replyTo?: string;
  type: "m.replace" | "m.annotation" | "m.thread" | "m.reference" | string;
}
export interface MatrixReactionEvent extends MatrixRawEvent {
  added?: boolean;
  key: string;
  relatesToEventId: string;
}
export interface MatrixInviteEvent {
  inviter?: string;
  raw: unknown;
  roomId: string;
}
export interface MatrixSyncEvent {
  class: "state" | "ephemeral" | "accountData" | "toDevice" | "membership" | "redaction" | "raw" | string;
  content: { [key: string]: unknown};
  decrypted?: boolean;
  encrypted?: boolean;
  eventId?: string;
  nextBatch?: string;
  originServerTs?: number /* int64 */;
  raw: unknown;
  roomId?: string;
  section?: string;
  sender?: string;
  stateKey?: string;
  type: string;
}
export interface MatrixRoomThreadSummary {
  lastReplyTs?: number /* int64 */;
  replyCount?: number /* int */;
  root: MatrixMessageEvent;
}
export interface MatrixFetchMessagesResult {
  messages: MatrixMessageEvent[];
  nextCursor?: string;
}
export interface MatrixFetchMessageResult {
  message?: MatrixMessageEvent | null;
}
export interface MatrixUploadMediaResult {
  contentUri: string;
  raw: unknown;
}
export interface MatrixDownloadMediaResult {
  bytesBase64: string;
}
export interface MatrixUploadEncryptedMediaResult {
  contentUri: string;
  file: MatrixEncryptedFile;
  raw: unknown;
}
export interface MatrixOpenDMResult {
  raw: unknown;
  roomId: string;
}
export interface MatrixJoinRoomResult {
  raw: unknown;
  roomId: string;
}
export interface MatrixJoinedRoomsResult {
  raw: unknown;
  roomIds: string[];
}
export interface MatrixUserInfo {
  avatarUrl?: string;
  displayName?: string;
  raw: unknown;
  userId: string;
}
export interface MatrixListRoomThreadsResult {
  nextCursor?: string;
  threads: MatrixRoomThreadSummary[];
}
export interface MatrixGetUserOptions {
  userId: string;
}
export interface MatrixOwnDisplayNameResult {
  displayName?: string;
  raw: unknown;
}
export interface MatrixSetOwnDisplayNameOptions {
  displayName: string;
}
export interface MatrixOwnAvatarURLResult {
  avatarUrl?: string;
}
export interface MatrixSetOwnAvatarURLOptions {
  avatarUrl: string;
}
