package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/gzuidhof/tygo/tygo"
)

func main() {
	root := filepath.Join("internal", "core")
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, root, nil, parser.ParseComments)
	check(err)

	var out bytes.Buffer
	var operations []operationSpec
	var exportedSpecs []*ast.TypeSpec
	out.WriteString("// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.\n\n")
	writeMautrixInterfaces(&out)
	pkgNames := make([]string, 0, len(pkgs))
	for name := range pkgs {
		pkgNames = append(pkgNames, name)
	}
	sort.Strings(pkgNames)
	for _, pkgName := range pkgNames {
		pkg := pkgs[pkgName]
		fileNames := make([]string, 0, len(pkg.Files))
		for name := range pkg.Files {
			fileNames = append(fileNames, name)
		}
		sort.Strings(fileNames)
		for _, fileName := range fileNames {
			file := pkg.Files[fileName]
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}
				if gen.Tok == token.CONST {
					operations = append(operations, collectOperations(gen)...)
					continue
				}
				if gen.Tok != token.TYPE {
					continue
				}
				spec, ok := gen.Specs[0].(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := spec.Type.(*ast.StructType); !ok || !strings.HasPrefix(spec.Name.Name, "Matrix") {
					continue
				}
				exportedSpecs = append(exportedSpecs, spec)
			}
		}
	}
	generatedTypes, err := generateTypescriptTypes(fset, exportedSpecs)
	check(err)
	out.WriteString(generatedTypes)
	check(os.WriteFile(filepath.Join("..", "src", "generated-runtime-types.ts"), out.Bytes(), 0o644))

	var opsOut bytes.Buffer
	writeOperations(&opsOut, operations)
	check(os.WriteFile(filepath.Join("..", "src", "generated-runtime-operations.ts"), opsOut.Bytes(), 0o644))
}

func generateTypescriptTypes(fset *token.FileSet, specs []*ast.TypeSpec) (string, error) {
	var src bytes.Buffer
	for _, spec := range specs {
		extendEmbeddedTypes(spec.Type)
		src.WriteString("type ")
		if err := printer.Fprint(&src, fset, spec); err != nil {
			return "", err
		}
		src.WriteString("\n\n")
	}
	return tygo.ConvertGoToTypescript(src.String(), tygo.PackageConfig{
		FallbackType:     "unknown",
		PreserveComments: "none",
		TypeMappings: map[string]string{
			"event.EncryptedFileInfo": "MatrixEncryptedFile",
			"json.RawMessage":         "unknown",
		},
	})
}

func extendEmbeddedTypes(expr ast.Expr) {
	ast.Inspect(expr, func(node ast.Node) bool {
		field, ok := node.(*ast.Field)
		if ok && len(field.Names) == 0 && field.Tag == nil {
			field.Tag = &ast.BasicLit{
				Kind:  token.STRING,
				Value: "`json:\",inline\" tstype:\",extends\"`",
			}
		}
		return true
	})
}

func writeMautrixInterfaces(out *bytes.Buffer) {
	out.WriteString("export interface MatrixEncryptedFileKey {\n")
	out.WriteString("  alg: \"A256CTR\";\n")
	out.WriteString("  ext: true;\n")
	out.WriteString("  k: string;\n")
	out.WriteString("  key_ops: [\"encrypt\", \"decrypt\"];\n")
	out.WriteString("  kty: \"oct\";\n")
	out.WriteString("}\n\n")
	out.WriteString("export interface MatrixEncryptedFile {\n")
	out.WriteString("  hashes: { sha256: string };\n")
	out.WriteString("  iv: string;\n")
	out.WriteString("  key: MatrixEncryptedFileKey;\n")
	out.WriteString("  url: string;\n")
	out.WriteString("  v: \"v2\";\n")
	out.WriteString("}\n\n")
}

type operationSpec struct {
	Method   string
	Op       string
	Request  string
	Response string
	Optional bool
}

func collectOperations(gen *ast.GenDecl) []operationSpec {
	var ops []operationSpec
	for _, raw := range gen.Specs {
		spec, ok := raw.(*ast.ValueSpec)
		if !ok || spec.Doc == nil || len(spec.Values) == 0 {
			continue
		}
		op, ok := operation(spec.Doc.Text())
		if !ok {
			continue
		}
		if lit, ok := spec.Values[0].(*ast.BasicLit); ok {
			op.Op = constant.StringVal(constant.MakeFromLiteral(lit.Value, lit.Kind, 0))
		}
		ops = append(ops, op)
	}
	return ops
}

func operation(doc string) (operationSpec, bool) {
	for _, line := range strings.Split(doc, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "ts:operation ") {
			continue
		}
		parts := strings.Fields(strings.TrimPrefix(line, "ts:operation "))
		if len(parts) < 4 {
			panic("ts:operation requires method op request response")
		}
		op := operationSpec{
			Method:   parts[0],
			Op:       parts[1],
			Request:  parts[2],
			Response: parts[3],
		}
		if len(parts) > 4 && parts[4] == "optional" {
			op.Optional = true
		}
		return op, true
	}
	return operationSpec{}, false
}

func writeOperations(out *bytes.Buffer, ops []operationSpec) {
	out.WriteString("// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.\n\n")
	imports := map[string]bool{}
	for _, op := range ops {
		if op.Request != "-" {
			imports[op.Request] = true
		}
		if op.Response != "void" {
			imports[op.Response] = true
		}
	}
	names := make([]string, 0, len(imports))
	for name := range imports {
		names = append(names, name)
	}
	sort.Strings(names)
	if len(names) > 0 {
		out.WriteString("import type {\n")
		for _, name := range names {
			fmt.Fprintf(out, "  %s,\n", name)
		}
		out.WriteString("} from \"./generated-runtime-types\";\n\n")
	}
	out.WriteString("export interface MatrixCoreOperations {\n")
	for _, op := range ops {
		fmt.Fprintf(out, "  %s(%s): Promise<%s>;\n", op.Method, operationInterfaceParam(op), op.Response)
	}
	out.WriteString("}\n\n")
	out.WriteString("export abstract class MatrixCoreOperationCaller implements MatrixCoreOperations {\n")
	out.WriteString("  protected abstract call<T>(operation: string, payload?: unknown): Promise<T>;\n\n")
	for _, op := range ops {
		fmt.Fprintf(out, "  %s(%s): Promise<%s> {\n", op.Method, operationParam(op), op.Response)
		fmt.Fprintf(out, "    return this.call<%s>(\"%s\"%s);\n", op.Response, op.Op, operationArg(op))
		out.WriteString("  }\n\n")
	}
	out.WriteString("}\n")
}

func operationParam(op operationSpec) string {
	if op.Request == "-" {
		return ""
	}
	if op.Optional {
		return fmt.Sprintf("options: %s = {}", op.Request)
	}
	return fmt.Sprintf("options: %s", op.Request)
}

func operationInterfaceParam(op operationSpec) string {
	if op.Request == "-" {
		return ""
	}
	if op.Optional {
		return fmt.Sprintf("options?: %s", op.Request)
	}
	return fmt.Sprintf("options: %s", op.Request)
}

func operationArg(op operationSpec) string {
	if op.Request == "-" {
		return ""
	}
	return ", options"
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
